### ISSUE TITLE
sqrt() on < 1 fails with const assignment

### ISSUE THREAD

**Issue by atengberg** [AlexSp3/Basenumber.js#5]
While rewriting a stats library with Basenumber in common module format, I found sqrt for any value < 1 will throw const assignment exception due to:

https://github.com/AlexSp3/Basenumber.js/blob/c7cd52939e4c2fef47b1ed352f556882b01f24d9/BaseNumber.js#L318

Trying a hot fix using [...] to make it mutable by char then results in maximum call stack size exceeded error.

**Comment by AlexSp3** [comment]
It is solved! Although the error was due to trying to modify a string, all that algorithm was not necessary because doing `cmp(x, LN2) == 1` implies that `b` is always positive, so a simple split should do the floor.

https://github.com/AlexSp3/Basenumber.js/blob/731a5439c5230718d052021f9b738e0f489c9f41/BaseNumber.js#L322

There was a fundamental bug in the cmp function, which causes `cmp(x, LN2)` to return 1 for some x <= LN2.

**Comment by atengberg** [comment]
Awesome, thank you! Possible feature request... singleton recycling factories for a given set of configuration values? Even better, use a TypedArray collection (:
